### ISSUE TITLE
Add subnetwork contract

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-contract#122]
## Summary
Create new `Subnet` contract for NeoFS sidechain which provides the functionality to create and work with subnets. It works with subnet IDs and info structures defined in NeoFS API V2 protocol (https://github.com/nspcc-dev/neofs-api/issues/180). Also operates with public keys and owner IDs.

## Task

Create `Subnet` contract with methods;

- [x] `Put(bytes id, bytes owner, bytes info)` method. It must check uniqueness of the identifier. If called by required number of alphabet nodes, saves the subnet, otherwise produces corresponding notification.

- [x] `Delete(bytes ID)` method. It must require the method to be called by the subnet owner only. It can fail if subnet is missing.

- [x] `AddNodeAdmin(bytes subnetID, interop.PublicKey adminPublicKey)` which extends the list of admin keys which are allowed to manage whitelist of subnet nodes. It must require the method to be called by subnet owner only.

- [x] `RemoveNodeAdmin(bytes subnetID, interop.PublicKey adminPublicKey)` which is same as `AddNodeAdmin` but removal.

- [x] `AddNode(bytes subnetID, interop.PublicKey publicKey)` which extends the list of node IDs which are allowed to entry the subnet. It must require the method to be called by subnet owner or node admin only.

- [x] `RemoveNode(bytes subnetID, interop.PublicKey publicKey)` which is same as `AddNode` but with removal. Produces corresponding notification. Produces corresponding notification.

- [x] `ListNodes(bytes subnetID) []bytes` which returns list of IDs added via `AddNode`.

- [x] `AddClientAdmin(bytes subnetID, bytes groupID, interop.PublicKey adminPublicKey)` which appends the list of admin keys for the specific group which are allowed to manage whitelist of subnet clients. It must require the method to be called by subnet owner only.

- [x] `RemoveClientAdmin(bytes subnetID, bytes groupID, interop.PublicKey adminPublicKey)` which is same as `AddClientAdmin` but removal.

- [x] `AddUser(bytes subnetID, bytes groupID, bytes ownerID) ` which extends list of users which are allowed to bind their containers to the subnet. It must require the method to be called by subnet owner or client group admin only.

- [x]  `RemoveUser(bytes subnetID, bytes groupID, bytes ownerID)` which is same as `AddUser` but with removal.

- [x] `ListUsers(bytes subnetID) []bytes` which returns list of IDs added via `AddUser`.

After that:

- [ ] Test contract via internal test framework.
- [ ] Write contract API and docs.
